#theme = gruvbox-material
#theme = gruber-darker
#theme = tokyonight_night
# theme = Monokai Remastered
# theme = Jellybeans
theme = Cursor Dark
# theme = nightfox
# theme = Aura
# theme = Aurora
# theme = ayu
# theme = Bright Lights
# theme = carbonfox
# theme = catppuccin-mocha
font-size = 24

#background-opacity = 0.8
mouse-hide-while-typing = true

window-padding-x = 4

cursor-style = block
cursor-style-blink = false
shell-integration-features = no-cursor

confirm-close-surface = false

window-decoration = true
